# Generated by Django 2.2.3 on 2019-07-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domain_agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('parent_rule_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rule_structure', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('rate_constant', models.CharField(max_length=100)),
                ('kinetic_constant', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=100)),
                ('estimated', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('model_source', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('agents', models.CharField(max_length=100)),
                ('domains', models.CharField(max_length=100)),
                ('agent_domain_pairs', models.CharField(max_length=100)),
            ],
        ),
    ]
